# defaults:  
#   - _self_  
  # - override hydra/hydra_logging: disabled  
  # - override hydra/job_logging: disabled  

save_dir: ???
audio_files: ???
classes: ???
instructions: ???

target_name: label # if multiclass, this is the target column name
title: hydrophone_labeller

# default args
default_classes: ["multiple classes","uncertain","noise"] # include these default columns as buttons when the user is labeling
objective_type: multiclass # optional multiclass or multilabel. If multiclass, only one label can be selected
sample_weights: null # a path to a file that contains a sample weight to get the proportion that this sample should appear next. This is useful for active learning.
start_segments: null # the filename with the filename and segment start


# Gradio args
share: false
deploy: false


  
hydra:  
  output_subdir: null  
  run:  
    dir: .

